---
nfs_client:
  - nfs_mount: /media/synology/music
    nfs_server: 192.168.2.50
    nfs_dir: /volume1/music
  - nfs_mount: /media/synology/tv
    nfs_server: 192.168.2.50
    nfs_dir: /volume1/tv
  - nfs_mount: /media/synology/roms
    nfs_server: 192.168.2.50
    nfs_dir: /volume1/roms
  - nfs_mount: /media/synology/plex_metadata
    nfs_server: 192.168.2.50
    nfs_dir: /volume1/plex_metadata
  - nfs_mount: /media/synology/homes
    nfs_server: 192.168.2.50
    nfs_dir: /volume1/homes
