---
- name: "Install common pre-reqs"
  package:
    name:
      - autoconf
      - autogen
      - automake
      - gcc
      - git
      - make
    state: present

- name: "Install pre-requisites debian"
  package:
    name:
      - libmnl-dev
      - libuv1-dev
      - pkg-config
      - uuid-dev
      - zlib1g-dev
    state: present
  when: ansible_os_family == "Debian"

- block:
  - name: "Install pre-prereqs"
    package:
      name:
        - epel-release
        # needed to get killall
        - psmisc
      state: present

  - name: "Install pre-requisites redhat"
    package:
      name:
        - curl
        - gcc
        - jq
        - libmnl-devel
        - libuuid-devel
        - nodejs
        - pkgconfig
        - zlib-devel
      state: present
  when: ansible_os_family == "RedHat"

- name: "Check for clone"
  stat:
    path: /tmp/netdata
  register: netdata_clone

- name: "Clone repo"
  git:
    clone: yes
    repo: https://github.com/firehol/netdata.git
    dest: /tmp/netdata
  when: netdata_clone.stat.exists == False

- name: "Installation"
  command: ./netdata-installer.sh --dont-wait --libs-are-really-here
  args:
    chdir: /tmp/netdata
    creates: /etc/netdata
  notify: "kill netdata"

- name: "Netdata Conf"
  template:
    src: netdata.conf.j2
    dest: /etc/netdata/netdata.conf
    owner: root
    group: root
    mode: 0664
  notify: "restart netdata"

- name: "Service enabled"
  service:
    name: netdata
    enabled: yes
