---
# tasks file for roles/docker
- name: Ensure that APT works with the https method
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - python3-pip
    - software-properties-common

- name: Install docker GPG key
  apt_key:
    keyserver: "{{ docker_keyserver }}"
    id: "{{ docker_keyserver_id }}"
    state: present

- name: Add docker apt repository
  apt_repository:
    repo: "{{ docker_apt_repo }}"
    state: present

- name: Update cache
  apt:
    update_cache: true

- name: Install docker package
  apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
  notify: Start Docker

- name: Install docker pip
  pip:
    name: docker-compose
    executable: /usr/bin/pip3
    state: present
