---
# tasks file for roles/docker
- name: Ensure that APT works with the https method
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common

- name: Install docker GPG key
  apt_key:
    keyserver: "{{ docker_keyserver }}"
    id: "{{ docker_keyserver_id }}"
    state: present

- name: Add docker apt repository
  apt_repository:
    repo: "{{ docker_apt_repo }}"
    state: present

- name: Purge the old repo if it exists
  apt:
    name: "{{ item }}"
    purge: true
  ignore_errors: true
  loop:
    - "lxc-docker*"
    - "docker.io*"

- name: Update cache
  apt:
    update_cache: true

- name: Install docker package
  apt:
    name: docker-engine
    state: present
  notify: Start Docker

- name: Install docker pip
  pip:
    name: "{{ item }}"
    state: present
  with_items:
    - docker-py
    - docker-compose
