---
- name: Install NFS client
  package:
    name: nfs-utils
    state: present
  when: ansible_distribution == 'CentOS'

- name: Install NFS client
  package:
    name: nfs-common
    state: present
  when: ansible_os_family == 'Debian'

- name: Turn on NFS client
  service:
    name: rpcbind
    state: started
    enabled: yes

- name: Ensure mount dir exists
  file:
    path: "{{ item.nfs_mount }}"
    state: directory
  with_items: "{{ nfs_client }}"

- name: Make the mount
  mount:
    name: "{{ item.nfs_mount }}"
    src: "{{ item.nfs_server }}:/{{ item.nfs_dir }}"
    fstype: nfs
    state: mounted
  with_items: "{{ nfs_client }}"
