---
- hosts: all
  gather_facts: false
  pre_tasks:
    - name: Install python if it's missing
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python3-minimal)

- import_playbook: initial.yml
